{% set name = "dustgoggles" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dustgoggles-{{ version }}.tar.gz
  sha256: 32e7040e6caea1919e0f062aef77a69bee56db24b5e0fd9b856e2215206a47e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - cytoolz
    - more-itertools
    - python >=3.9

test:
  imports:
    - dustgoggles
  commands:
    - pip check
  requires:
    - pip

about:

  home: https://github.com/millionconcepts/dustgoggles
  summary: ready for anything in these goggles -- a marslab project
  description: dustgoggles is a utility library for the `marslab` ecosystem. It contains a variety of generic utilities, text-parsing tools, a framework for domain-specific functional languages, and an in-memory cache framework.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sierra-MC
    - m-stclair
